language: python
python:
    - "3.6"

sercices:
    - docker

before_script: pip install docker-compose

script:
    - docker-compose run app sh -c "coverage run python manage.py test && flake8"
    
after_success:
    - coveralls